Repository AY2122S1-CS2103-T16-1/tp, pull requests merged in 2021-10, with the labels that each got.

#41 Update user guide with unix commands
  docs/UserGuide.md
Labels: type.Documentation

#42 Update user guide on folder removal
  docs/UserGuide.md
Labels: type.Documentation

#44 Update existing commands to unix format
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.Story

#48 Add list folder command and update GUI to display list of folders
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListFoldersCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/FolderCard.java
  src/main/java/seedu/address/ui/FolderListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/FolderListCard.fxml
  src/main/resources/view/FolderListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/logic/commands/ListFoldersCommandTest.java
Labels: type.Story

#55 Update UG with find folders command
  docs/UserGuide.md
Labels: type.Documentation, hacktoberfest-accepted

#66 Update index page with UNIon details
  docs/index.md
Labels: type.Documentation

#67 Re-merge edit folder name command
  src/main/java/seedu/address/logic/commands/EditFolderNameCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditFolderNameCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/folder/Folder.java
  src/main/java/seedu/address/model/folder/UniqueFolderList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddToFolderCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateFolderCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteFolderCommandTest.java
  src/test/java/seedu/address/logic/commands/EditFolderNameCommandTest.java
  src/test/java/seedu/address/logic/parser/EditFolderNameCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Story

#85 Update DG with view folders details
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Documentation

#79 Update GUI to be able to display contacts in folder
  src/main/java/seedu/address/ui/FolderCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/FolderListCard.fxml
Labels: type.Story

#93 Abstract typical folders to separate file
  src/test/java/seedu/address/storage/JsonAdaptedFolderTest.java
Labels: type.Bug, priority.High, severity.High, hacktoberfest-accepted
